version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    container_name: oea-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - '9200:9200'
    volumes:
      - esdata:/usr/share/elasticsearch/data

  weaviate:
    image: semitechnologies/weaviate:1.18.0
    container_name: oea-weaviate
    environment:
      - QUERY_DEFAULTS_LIMIT=20
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/data
    ports:
      - '8080:8080'
    volumes:
      - weaviate-data:/data

volumes:
  esdata:
  weaviate-data: